import {calculate,won} from './domain.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(p){const r=await fetch(p);if(!r.ok)throw Error(p+': '+r.status);return r.json();}
async function text(p){const r=await fetch(p);if(!r.ok)throw Error(p+': '+r.status);return r.text();}
let corpus,rates,limit=50,selected='art-55';
function images(a){return (a.images||[]).map((i,n)=>`<figure><img class="source-image" src="/${esc(i.localPath)}" alt="${esc(a.label)} 공식 원본 표·수식 ${n+1}"><figcaption class="meta">공식 원본 이미지 · ${a.id==='art-55'?'세율표 전사 대조 기록 있음. 대체 텍스트에는 최고구간 기초세액 누락이 있어 이미지와 대조했습니다.':'내용 검토 대기. 본문 대체 텍스트만으로 판단하지 마세요.'}</figcaption></figure>`).join('');}
function rateTable(){return `<h4>이미지와 대조한 제55조 제1항 표</h4><table><thead><tr><th>과세표준 상한</th><th>직전 경계의 세액</th><th>초과분 세율</th></tr></thead><tbody>${rates.rows.map(r=>`<tr><td>${r.upperBound===null?'10억 원 초과':Number(r.upperBound).toLocaleString()+'원 이하'}</td><td>${Number(r.baseTax).toLocaleString()}원</td><td>${r.ratePercent}%</td></tr>`).join('')}</tbody></table><p class="meta">둘째 구간부터 직전 경계 초과액에 해당 세율을 적용하여 기초세액에 더합니다.</p>`;}
function articleHTML(a){return `<h3>${esc(a.label)}</h3><p class="meta">${a.deleted?'삭제 조문':a.id==='art-55'?'제1항 기본 세율 수치만 부분 구현 · 조문 전체 아님':'원문 수집 완료 · 의미 검토·분류 대기'}</p><a href="${esc(a.sourceUrl)}" target="_blank" rel="noopener">국가법령정보센터 원문 ↗</a>${a.images?.length?'<p class="notice">원문 이미지와 대체 텍스트를 함께 보존합니다. 대체 텍스트는 누락·오류가 있을 수 있으므로 수식·표는 이미지를 확인하세요.</p>':''}${a.id==='art-55'?rateTable():''}<div class="source">${esc(a.text)}</div>${images(a)}${a.id==='art-55'?'<a href="#demo">수치 모델과 주석으로 이동 ↑</a>':'<p class="notice">아직 수학적 정의 가능성을 검토하지 않았습니다. 미구현을 수학적 불가능으로 판단하지 않습니다.</p>'}`;}
function select(id){selected=id;$('detail').innerHTML=articleHTML(corpus.articles.find(a=>a.id===id));document.querySelectorAll('.article').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));}
function render(){const q=$('query').value.trim(),f=$('filter').value;const rows=corpus.articles.filter(a=>(!q||`${a.label} ${a.text}`.includes(q))&&(f==='all'||f==='active'&&!a.deleted||f==='deleted'&&a.deleted||f==='implemented'&&a.id==='art-55'));$('count').textContent=`${rows.length}개 조문 · ${Math.min(limit,rows.length)}개 표시`;$('articles').innerHTML=rows.slice(0,limit).map(a=>`<button class="article ${a.id===selected?'selected':''}" data-id="${esc(a.id)}"><b>${esc(a.label)}</b><small>${a.deleted?'삭제':a.id==='art-55'?'기본 세율 부분 Lean 구현':'분류 대기'}</small></button>`).join('');$('more').hidden=rows.length<=limit;document.querySelectorAll('.article').forEach(b=>b.addEventListener('click',()=>select(b.dataset.id)));if(rows.length&&!rows.some(a=>a.id===selected))select(rows[0].id);}
$('tax-form').addEventListener('submit',e=>{e.preventDefault();try{if(!$('confirmed').checked)throw Error('과세표준이라는 전제를 먼저 확인해 주세요.');const r=calculate($('base').value.trim());const next=BigInt(r.base)<1000000000000n?calculate((BigInt(r.base)+1n).toString()):null;$('result').innerHTML=`<h3>기본 산출세액의 수학적 값</h3><p class="amount">${won(r.scaled)} 원</p><p>${next?`과세표준이 1원 늘면 기본 세액은 <b>${won(BigInt(next.scaled)-BigInt(r.scaled))}원</b> 증가합니다.`:'화면의 입력 상한에 도달했습니다.'}</p><table><thead><tr><th>구간에 속하는 금액</th><th>세율</th><th>기여 세액</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${BigInt(x.amount).toLocaleString()}원</td><td>${x.rate}%</td><td>${won(x.scaled)}원</td></tr>`).join('')}</tbody></table><p class="notice">법률·세무 검토가 아닌 제한된 모델의 결과입니다. 연말정산 납부·환급액이 아니며 법정 끝수처리를 적용하지 않았습니다.</p>`;}catch(err){$('result').textContent=err.message;}});
$('base').addEventListener('input',()=>{$('confirmed').checked=false;$('result').textContent='입력값이 바뀌었습니다. 전제를 확인하고 다시 계산해 주세요.'});$('confirmed').addEventListener('change',()=>{$('result').textContent='입력 전제로 다시 계산해 주세요.'});
async function start(){
 let v;[corpus,v,rates]=await Promise.all([get('/data/corpus.json'),get('/reports/verification.json'),get('/data/article55-rates.json')]);
 $('metrics').innerHTML=[[corpus.articles.length,'전체 본문 조문','삭제 조문 포함'],[corpus.articles.filter(a=>!a.deleted).length,'현존 조문','전체 분류·검토는 진행 전'],[1,'부분 구현 조문','제55조 제1항 기본 세율'],[v.theoremCount,'검증된 Lean 정리','일반 정리와 사례 포함']].map(([n,l,s])=>`<div class="metric"><strong>${n}</strong>${l}<small>${s}</small></div>`).join('');
 const m=corpus.metadata;$('edition').textContent=`기준일 ${m.asOfDate} · 본문 시행 ${m.effectiveDate} · 법률 제${m.actNumber}호 · 특정 귀속연도의 연말정산 규정 전체를 확정한 자료가 아닙니다.`;
 render();select('art-55');$('mapped-source').innerHTML=articleHTML(corpus.articles.find(a=>a.id==='art-55'));
 $('lean-code').textContent=await text('/lean/Basic.lean');$('verification').textContent=JSON.stringify(v,null,2);
 try{$('solar-code').textContent=await text('/lean/Solar.lean')+'\n\n'+await text('/lean/Agreement.lean')}catch{$('solar-code').textContent='공동 작성 과제 평가 중입니다. 검증을 통과한 정의만 여기에 채택합니다.'}
 for(const [path,label] of [['/reports/solar/assessment.md','공동 작성·검토 평가'],['/reports/source.md','원문 수집·이미지 표 대조']]){try{const t=await text(path);$('joint-review').insertAdjacentHTML('beforeend',`<h4>${esc(label)}</h4><pre>${esc(t)}</pre>`)}catch{}}
 $('addenda').innerHTML=corpus.addenda.map(a=>`<details><summary>${esc(a.label)}</summary>${a.images?.length?'<p class="notice">원문 이미지와 대체 텍스트를 함께 보존합니다. 대체 텍스트는 누락·오류가 있을 수 있으므로 수식·표는 이미지를 확인하세요.</p>':''}${a.id==='art-55'?rateTable():''}<div class="source">${esc(a.text)}</div>${images(a)}</details>`).join('');
 for(const id of ['query','filter'])$(id).addEventListener(id==='query'?'input':'change',()=>{limit=50;render()});$('more').addEventListener('click',()=>{limit+=50;render()});
}
start().catch(e=>{$('error').hidden=false;$('error').textContent='자료를 불러오지 못했습니다. '+e.message;});
