import './settlement-ui.js';
import {calculate,won} from './domain.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(p){const r=await fetch(p);if(!r.ok)throw Error(p+': '+r.status);return r.json();}
async function text(p){const r=await fetch(p);if(!r.ok)throw Error(p+': '+r.status);return r.text();}
const categoryNames={direct:'직접 형식화 후보',conditional:'가정하에 형식화 후보',structural:'구조 형식화 후보',unformalized:'현재 미형식화',deleted:'삭제',pending:'분류 대기'};
let classification,byClass=new Map();
let corpus,rates,limit=50,selected='art-55';
function images(a){return (a.images||[]).map((i,n)=>`<figure><img class="source-image" src="/${esc(i.localPath)}" alt="${esc(a.label)} 공식 원본 표·수식 ${n+1}"><figcaption class="meta">공식 원본 이미지 · ${a.id==='art-55'?'세율표 전사 대조 기록 있음. 대체 텍스트에는 최고구간 기초세액 누락이 있어 이미지와 대조했습니다.':'내용 검토 대기. 본문 대체 텍스트만으로 판단하지 마세요.'}</figcaption></figure>`).join('');}
function rateTable(){return `<h4>이미지와 대조한 제55조 제1항 표</h4><table><thead><tr><th>과세표준 상한</th><th>직전 경계의 세액</th><th>초과분 세율</th></tr></thead><tbody>${rates.rows.map(r=>`<tr><td>${r.upperBound===null?'10억 원 초과':Number(r.upperBound).toLocaleString()+'원 이하'}</td><td>${Number(r.baseTax).toLocaleString()}원</td><td>${r.ratePercent}%</td></tr>`).join('')}</tbody></table><p class="meta">둘째 구간부터 직전 경계 초과액에 해당 세율을 적용하여 기초세액에 더합니다.</p>`;}
function classificationHTML(a){const c=byClass.get(a.id);if(!c)return '';return `<div class="classification-note"><b>${esc(categoryNames[c.category]||c.category)} · ${c.reviewStatus==='source-reviewed'?'공동 원문 검토 기록':'검토 상태: '+esc(c.reviewStatus)}</b><p>${esc(c.rationale)}</p>${c.evidence?`<details><summary>분류에 사용한 원문 발췌</summary><blockquote>${esc(c.evidence)}</blockquote></details>`:''}<h4>표현 가능한 부분</h4><ul>${(c.formalizable||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h4>외부 판단·미해결 부분</h4><ul>${(c.unresolved||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="meta">참조·외부 의존: ${esc((c.dependencies||[]).join(' · ')||'별도 기록 없음')}</p></div>`;}
function articleHTML(a){return `<h3>${esc(a.label)}</h3><p class="meta">${a.deleted?'삭제 조문':a.id==='art-55'?'제1항 기본 세율 수치만 부분 구현 · 조문 전체 아님':'아래 분류는 표현 가능성의 잠정 평가이며 조문 전체 구현 완료가 아닙니다.'}</p><a href="${esc(a.sourceUrl)}" target="_blank" rel="noopener">국가법령정보센터 원문 ↗</a>${classificationHTML(a)}${a.images?.length?'<p class="notice">원문 이미지와 대체 텍스트를 함께 보존합니다. 대체 텍스트에는 누락·오류가 있을 수 있습니다. 제55조 표 외의 이미지 내용은 별도 시각 검토 대기입니다.</p>':''}${a.id==='art-55'?rateTable():''}<div class="source">${esc(a.text)}</div>${images(a)}${a.id==='art-55'?'<a href="#demo">수치 모델과 주석으로 이동 ↑</a>':''}`;}

function select(id){selected=id;$('detail').innerHTML=articleHTML(corpus.articles.find(a=>a.id===id));document.querySelectorAll('.article').forEach(b=>b.classList.toggle('selected',b.dataset.id===id));}
function render(){const q=$('query').value.trim(),f=$('filter').value;const rows=corpus.articles.filter(a=>(!q||`${a.label} ${a.text}`.includes(q))&&(f==='all'||f==='active'&&!a.deleted||f==='deleted'&&a.deleted||f==='implemented'&&a.id==='art-55'||byClass.get(a.id)?.category===f));$('count').textContent=`${rows.length}개 조문 · ${Math.min(limit,rows.length)}개 표시`;$('articles').innerHTML=rows.slice(0,limit).map(a=>`<button class="article ${a.id===selected?'selected':''}" data-id="${esc(a.id)}"><b>${esc(a.label)}</b><small>${(categoryNames[byClass.get(a.id)?.category]||'분류 대기')+(a.id==='art-55'?' · 기본 세율 부분 구현':'')}</small></button>`).join('');$('more').hidden=rows.length<=limit;document.querySelectorAll('.article').forEach(b=>b.addEventListener('click',()=>select(b.dataset.id)));if(rows.length&&!rows.some(a=>a.id===selected))select(rows[0].id);}
function renderIssues(){let shown=40;const input=$('issue-query'),list=$('issue-list');function paint(){const q=input.value.trim();const rows=classification.articles.filter(c=>c.category!=='deleted'&&(c.unresolved||[]).length).filter(c=>!q||`${corpus.articles.find(a=>a.id===c.id).label} ${c.unresolved.join(' ')}`.includes(q));$('issue-count').textContent=`${rows.length}개 조문 · ${Math.min(shown,rows.length)}개 표시`;$('issues-more').hidden=shown>=rows.length;list.innerHTML=rows.slice(0,shown).map(c=>`<details><summary>${esc(corpus.articles.find(a=>a.id===c.id).label)} · ${esc(categoryNames[c.category])}</summary><ul>${c.unresolved.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="meta">입법 결함 판정이 아닌 형식화·참조·외부 판단의 검토 기록입니다.</p></details>`).join('');}input.addEventListener('input',()=>{shown=40;paint()});$('issues-more').addEventListener('click',()=>{shown+=40;paint()});paint();}
$('tax-form').addEventListener('submit',e=>{e.preventDefault();try{if(!$('confirmed').checked)throw Error('과세표준이라는 전제를 먼저 확인해 주세요.');const r=calculate($('base').value.trim());const next=BigInt(r.base)<1000000000000n?calculate((BigInt(r.base)+1n).toString()):null;$('result').innerHTML=`<h3>기본 산출세액의 수학적 값</h3><p class="amount">${won(r.scaled)} 원</p><p>${next?`과세표준이 1원 늘면 기본 세액은 <b>${won(BigInt(next.scaled)-BigInt(r.scaled))}원</b> 증가합니다.`:'화면의 입력 상한에 도달했습니다.'}</p><table><thead><tr><th>구간에 속하는 금액</th><th>세율</th><th>기여 세액</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${BigInt(x.amount).toLocaleString()}원</td><td>${x.rate}%</td><td>${won(x.scaled)}원</td></tr>`).join('')}</tbody></table><p class="notice">법률·세무 검토가 아닌 제한된 모델의 결과입니다. 연말정산 납부·환급액이 아니며 법정 끝수처리를 적용하지 않았습니다.</p>`;}catch(err){$('result').textContent=err.message;}});
$('base').addEventListener('input',()=>{$('confirmed').checked=false;$('result').textContent='입력값이 바뀌었습니다. 전제를 확인하고 다시 계산해 주세요.'});$('confirmed').addEventListener('change',()=>{$('result').textContent='입력 전제로 다시 계산해 주세요.'});
async function start(){
 let v;[corpus,v,rates,classification]=await Promise.all([get('/data/corpus.json'),get('/reports/verification.json'),get('/data/article55-rates.json'),get('/data/classification.json')]);byClass=new Map(classification.articles.map(c=>[c.id,c]));
 $('metrics').innerHTML=[[corpus.articles.length,'전체 본문 조문','삭제 조문 포함'],[classification.metadata.semanticReviewedArticles||0,'본문 의미 분류 검토','가능성 평가 · 증명 완료 아님'],['2025','귀속연도 정산 모형','지원 범위·외부 전제 확인 필요'],[v.theoremCount,'검증된 Lean 정리','일반 정리와 사례 포함']].map(([n,l,s])=>`<div class="metric"><strong>${n}</strong>${l}<small>${s}</small></div>`).join('');
 const m=corpus.metadata;$('edition').textContent=`기준일 ${m.asOfDate} · 본문 시행 ${m.effectiveDate} · 법률 제${m.actNumber}호 · 지도에는 개별 미래 시행 문구가 포함될 수 있어 조항별 적용일 확인이 필요합니다. 위 정산 모형은 별도 2025년 귀속 자료를 사용합니다.`;
 render();select('art-55');renderIssues();$('mapped-source').innerHTML=articleHTML(corpus.articles.find(a=>a.id==='art-55'));
 $('lean-code').textContent=await text('/lean/Basic.lean');$('verification').textContent=JSON.stringify(v,null,2);
 try{$('solar-code').textContent=await text('/lean/Solar.lean')+'\n\n'+await text('/lean/Agreement.lean')}catch{$('solar-code').textContent='공동 작성 과제 평가 중입니다. 검증을 통과한 정의만 여기에 채택합니다.'}
 for(const [path,label] of [['/reports/solar/assessment.md','공동 작성·검토 평가'],['/reports/source.md','원문 수집·이미지 표 대조']]){try{const t=await text(path);$('joint-review').insertAdjacentHTML('beforeend',`<h4>${esc(label)}</h4><pre>${esc(t)}</pre>`)}catch{}}
 $('addenda').innerHTML=corpus.addenda.map(a=>`<details><summary>${esc(a.label)}</summary>${a.images?.length?'<p class="notice">원문 이미지와 대체 텍스트를 함께 보존합니다. 대체 텍스트는 누락·오류가 있을 수 있으므로 수식·표는 이미지를 확인하세요.</p>':''}${a.id==='art-55'?rateTable():''}<div class="source">${esc(a.text)}</div>${images(a)}</details>`).join('');
 for(const id of ['query','filter'])$(id).addEventListener(id==='query'?'input':'change',()=>{limit=50;render()});$('more').addEventListener('click',()=>{limit+=50;render()});
}
start().catch(e=>{$('error').hidden=false;$('error').textContent='자료를 불러오지 못했습니다. '+e.message;});
