import {settle2025} from './settlement.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(name,label,value='0')=>`<label>${label}<input name="${name}" inputmode="numeric" value="${value}" maxlength="14"></label>`;
const check=(name,label)=>`<label class="check"><input type="checkbox" name="${name}">${label}</label>`;
const counts=(name,label,value='0')=>money(name,label,value);
$('settlement').innerHTML=`<p class="eyebrow">2025 · YEAR-END SETTLEMENT MODEL</p><h2>총급여에서 공제·정산 차액까지</h2><p>2025년 귀속 국세청 안내서와 정오표를 기준으로 한 <b>일반 근로소득자의 소득세</b> 계산 모형입니다. 아래 2026년 시행 조문 지도와 기준이 다릅니다.</p><div class="notice"><strong>법률·세무 검토 또는 신고 서비스를 대체하지 않습니다.</strong><p>공제 자격·증빙은 사용자가 확인한 입력입니다. 지방소득세·농어촌특별세, 감면, 복합소득, 이월·추징은 지원하지 않습니다. 의료비·기부금·복잡한 주택 공제는 별도 확인한 순액만 합산합니다.</p></div>
<form id="settlement-form" novalidate><div class="card"><h3>1. 계산 범위와 기본 입력</h3><div class="field-grid">${money('salary','연간 총급여 (비과세 제외·근무지 합산)','50000000')}${money('prepaid','기납부 소득세 (지방소득세 제외)','3000000')}<label>공제 경로<select name="route" id="settlement-route"><option value="itemized">특별공제 경로</option><option value="standard">표준세액공제 13만 원 경로</option></select></label></div><p id="route-notice" class="meta"></p>${check('complexCase','다른 종합소득, 중소기업 취업자 등 세액감면, 외국인 단일세율 또는 외국납부세액 관련 사항이 있습니다. (해당하면 계산 중단)')}${check('scopeConfirmed','2025년 귀속 대한민국 거주자의 일반 근로소득만 있으며, 지원하지 않는 세액감면·이월·추징이 없는 사례입니다.')}</div>
<div class="card"><h3>2. 인적·소득공제</h3><p class="meta">나이·소득·부양·중복공제 여부는 외부에서 확인합니다. 부양가족의 소득금액·총급여와 본인의 총급여를 혼동하지 마세요.</p><div class="field-grid">${counts('people','기본공제 인원 (본인 포함)','1')}${counts('aged','기본공제 대상 중 70세 이상')}${counts('disabled','기본공제 대상 중 장애인')}${money('nationalPension','공적연금 본인 공제대상 납부액')}</div>${check('woman','부녀자공제 요건 충족 (소득금액 3천만 원 이하·가족/세대 요건 확인)')}${check('singleParent','한부모공제 요건 충족 (부녀자공제와 중복 불가)')}<fieldset data-special><legend>특별소득공제 경로에서만 사용</legend><div class="field-grid">${money('healthInsurance','건강·장기요양보험 본인 공제대상액')}${money('employmentInsurance','고용보험 본인 공제대상액')}${money('specialCappedIncome','외부 확인 주택 관련 특별소득공제액 (종합한도 대상)')}</div></fieldset><details><summary>신용카드 등 소득공제 · 중복 없는 적격 사용액</summary><p class="meta">근로기간 지출·가족 자격·비공제 지출을 먼저 제외하세요. 월세 세액공제와 같은 지출을 중복 입력하지 않습니다. 문화체육은 7천만 원 이하, 체육시설은 2025.7.1 이후 적격 지출만 포함합니다.</p><div class="field-grid">${money('cardCredit','일반 신용카드')}${money('cardDebit','일반 직불·현금영수증')}${money('cardCulture','문화체육 적격 사용액')}${money('cardMarket','전통시장 적격 사용액')}${money('cardTransport','대중교통 적격 사용액')}</div></details><details><summary>그 밖의 소득공제 · 외부에서 확인한 금액</summary><p class="meta">이미 입력한 인적·연금·보험·카드 공제를 다시 넣지 않습니다. 개별 한도·중복을 외부에서 조정한 그 밖의 소득공제만 입력하세요. 제52조의 주택 관련 특별소득공제는 위 특별소득공제 칸으로 구분하고 여기에 넣지 않습니다. 종합한도 대상 항목만 카드공제와 합산해 2,500만 원 한도를 적용합니다.</p><div class="field-grid">${money('otherCappedIncomeDeduction','종합한도 대상의 기타 소득공제액')}${money('otherIncomeDeduction','종합한도 대상이 아닌 기타 소득공제 순액')}</div></details></div>
<div class="card"><h3>3. 세액공제</h3><p class="meta">근로소득세액공제는 자동 계산합니다. 아래는 2025년 요건을 충족하는 인원·본인 적격 납입액입니다.</p><div class="field-grid">${money('pensionSavings','연금저축 적격 납입액')}${money('irp','퇴직연금·IRP 본인 적격 납입액')}${counts('children','기본공제 대상 중 8세 이상 자녀·손자녀')}${counts('birthFirst','2025 출산·입양: 첫째 순위 인원')}${counts('birthSecond','2025 출산·입양: 둘째 순위 인원')}${counts('birthThirdPlus','2025 출산·입양: 셋째 이상 순위 인원')}</div><p class="meta">연금저축 한도 600만 원을 먼저 배분하고 퇴직연금과 합계 900만 원 한도를 적용합니다. ISA 전환 추가한도는 지원하지 않습니다. 자녀 나이 기준은 2025년 안내서 기준입니다.</p>${check('marriage','2025년 혼인신고 및 개인별 생애 1회 혼인세액공제 요건 충족')}
<fieldset data-special><legend>특별세액공제·월세 경로에서만 사용</legend><div class="field-grid">${money('insurance','일반 보장성보험 적격 보험료')}${money('disabledInsurance','장애인전용 보장성보험 적격 보험료')}${money('educationSelf','본인 적격 교육비')}${money('educationDisabled','장애인 특수교육 적격 교육비')}<label>취학 전·초중고 교육비 (사람별, 쉼표 구분)<input name="educationSchool" placeholder="예: 2000000,4000000"></label><label>대학생 교육비 (사람별, 쉼표 구분)<input name="educationUniversity" placeholder="예: 10000000,5000000"></label>${money('rent','주택·세대·주소 요건을 충족한 월세액')}${money('externalSpecialCredit','외부에서 확인한 기타 특별세액공제 순액')}</div><p class="meta">교육비는 장학금·회사 보전분을 제외하고 학생별 한도를 적용합니다. 본인 외 대학원은 제외합니다. 월세는 무주택·주택규모/기준시가·주소 일치·거주 등 요건을 먼저 확인해야 합니다.</p><p class="notice">의료비·기부금의 지출액을 그대로 ‘기타 특별세액공제 순액’에 넣으면 안 됩니다. 해당 자격·한도·법정 순서·당해연도 사용 가능액을 별도로 계산한 <b>공제 세액</b>만 입력합니다. 감면·이월공제를 대신 넣을 수 없습니다.</p></fieldset></div>
<div class="card">${check('factsConfirmed','공제 자격·증빙·중복 여부와 외부 입력 순액을 확인했습니다. 제한된 모델의 활용 예시이며, 납부·환급의 법적 확정이 아님을 이해합니다.')}<button type="submit">2025년 귀속 조건으로 계산</button><p class="meta">입력은 브라우저 안에서만 처리됩니다. 원천징수영수증 금액 칸에 맞춰 원 미만을 버리며, 개인 결정세액을 일괄 10원 단위로 내리지 않습니다.</p></div></form>
<div id="settlement-result" class="card" aria-live="polite" hidden></div><details class="card"><summary>2025년 원문 근거·공식·Lean 정의와 주석 인라인 보기</summary><div id="settlement-evidence"></div></details>`;
const form=$('settlement-form'),result=$('settlement-result');
function clear(){result.hidden=true;result.textContent='';}
function route(){const standard=$('settlement-route').value==='standard';form.querySelectorAll('[data-special]').forEach(f=>{f.disabled=standard;f.hidden=standard;});$('route-notice').textContent=standard?'표준 경로에서는 특별소득·특별세액·월세 입력을 계산에서 제외합니다. 기존 입력은 보관되지만 이 경로에서는 전송·적용하지 않습니다.':'특별 경로에서는 입력한 적격 공제를 적용하고 표준세액공제 13만 원을 적용하지 않습니다.';clear();}
form.addEventListener('input',e=>{clear();if(e.target.name!=='factsConfirmed')form.elements.factsConfirmed.checked=false;});form.addEventListener('change',clear);$('settlement-route').addEventListener('change',route);route();
const labels={salary:'총급여',deduction:'근로소득공제 · 제47조',income:'근로소득금액',personal:'인적공제 · 제50·51조',national:'공적연금보험료공제',health:'건강·고용보험·외부 확인 특별소득공제',card:'신용카드 등 소득공제 · 조특법126조의2',other:'그 밖의 소득공제 입력 합계',addback:'종합한도 초과액 (공제에서 제외)',base:'종합소득과세표준',assessed:'종합소득산출세액 · 제55조',earned:'근로소득세액공제 · 제59조',pension:'연금계좌세액공제',child:'자녀세액공제',birth:'출산·입양세액공제',marriage:'혼인세액공제',insurance:'보험료세액공제',education:'교육비세액공제',rent:'월세세액공제',externalSpecial:'외부 확인 기타 특별세액공제',standard:'표준세액공제',credits:'공제가능 세액 입력·계산 합계',determined:'결정세액 (0 하한)',prepaid:'기납부 소득세',balance:'계산상 차감징수세액',collectible:'소액부징수 반영 차감징수세액'};
form.addEventListener('submit',e=>{e.preventDefault();const input=Object.fromEntries(new FormData(form));for(const n of ['scopeConfirmed','factsConfirmed','complexCase','woman','singleParent','marriage'])input[n]=form.elements[n].checked;input.year='2025';result.hidden=false;try{const r=settle2025(input);const outcome=r.refund>0n?`환급 방향 ${r.refund.toLocaleString()}원`:r.additional>0n?`추가 납부 방향 ${r.additional.toLocaleString()}원`:'추가 징수 없음';result.innerHTML=`<p class="eyebrow">2025 · NATIONAL INCOME TAX ONLY</p><h3>입력한 전제에서의 정산 결과</h3><p class="amount">${outcome}</p><p>소득세만의 계산입니다. 지방소득세와 회사의 실제 지급·정산 절차는 포함하지 않습니다.</p><table><thead><tr><th>계산 단계</th><th>원</th></tr></thead><tbody>${Object.entries(labels).map(([key,label])=>`<tr><td>${label}</td><td>${r[key].toLocaleString()}</td></tr>`).join('')}</tbody></table><p class="meta">산출세액을 넘는 공제 합계 ${r.unusedCredits.toLocaleString()}원은 음수 세액을 만들지 않습니다. 그 금액의 이월·소멸 여부는 이 모형이 판단하지 않습니다. 양의 차감징수액 1,000원 미만은 소액부징수로 구분하며 음의 환급에는 적용하지 않습니다.</p><div class="notice"><strong>법률·세무 검토가 아닌 Lean 모델 활용 예시입니다.</strong><p>입력 자격·증빙은 검증하지 않았습니다. 지원 범위 밖 사례에 이 결과를 적용할 수 없습니다. 웹 계산의 표본 일치 검사와 Lean 정리의 증명은 별도로 기록합니다.</p></div>`;}catch(err){result.textContent=err.message;}});
(async()=>{for(const [path,label] of [['/reports/settlement-sources.md','2025년 공식 자료와 적용 범위'],['/data/settlement-2025-rules.json','공제별 수치 공식과 외부 전제'],['/lean/Settlement.lean','근로소득·공제·정산의 정의와 증명'],['/lean/SettlementSolar.lean','공동 작성한 정산 부호·보존 정리'],['/reports/solar/settlement-assessment.md','공동 검토·작성 기록']]){try{const r=await fetch(path);if(!r.ok)throw Error(r.status);const t=await r.text();$('settlement-evidence').insertAdjacentHTML('beforeend',`<h3>${esc(label)}</h3><pre>${esc(t)}</pre>`);}catch{$('settlement-evidence').insertAdjacentHTML('beforeend',`<p>${esc(label)}: 자료를 불러오지 못했습니다.</p>`);}}})();
